name: Playwright API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # ---------- Repo checkout ----------
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------- Node.js setup ----------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ---------- Backend dependencies ----------
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      # ---------- Backend build (opsiyonel) ----------
      - name: Build backend
        working-directory: backend
        run: npm run build || echo "No build script, skipping"

      # ---------- TestPlaywright dependencies ----------
      - name: Install Playwright dependencies
        working-directory: TestPlaywright
        run: npm ci

      # ---------- Backend server start ----------
      - name: Start backend server
        working-directory: backend
        run: |
          npm run start:dev &
          # Sağlıklı bekleme, port 3000 hazır olana kadar kontrol eder
          for i in {1..15}; do
            nc -z localhost 3000 && break
            echo "Waiting for backend to start..."
            sleep 2
          done

      # ---------- Playwright testleri ----------
      - name: Run Playwright tests
        working-directory: TestPlaywright
        run: npx playwright test --reporter=list

      # ---------- Test raporlarını yükle ----------
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: TestPlaywright/playwright-report/
